AllCops:
  TargetRubyVersion: 2.3
  Exclude:
  - '*.gemspec'
  - 'vendor/**/*'
ClassVars:
  Enabled: false
LineLength:
  Max: 120
MethodLength:
  Max: 20
Lint/UriEscapeUnescape:
  Enabled: false
Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'
Metrics/ClassLength:
  Max: 150
Metrics/CyclomaticComplexity:
  Max: 8
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
